# Generated by Django 4.2.7 on 2023-12-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_brutto',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_netto',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
